### ISSUE TITLE
Could not find module 'EsewaSDK'

### ISSUE THREAD

**Issue by riteshghimire9090** [iamnabink/flutter_esewa#3] opened 2023-08-08 18:01 UTC
Could not find module 'EsewaSDK' for target 'arm64-apple-ios'; found: x86_64-apple-ios-simulator, arm64-apple-ios-simulator, at: 

/ios/.symlinks/plugins/esewa_flutter_sdk/ios/EsewaSDK.framework/Modules/EsewaSDK.swiftmodule

**Comment by iamnabink** [comment] 2023-09-12 04:48
Please add more detail, Flutter version, platform and reproduction steps if possible.

**Comment by iamnabink** [comment] 2024-01-23 10:12
Hy @riteshghimire9090 I think you are stuck because of [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) package integration or `pod install` issue, make sure you have satisfied condition for `flutter_inappwebview` package impl, (like increase deployment target in Podfile : `platform :ios, 'x'` . or proper `pod install`.
Check-out [example project](https://github.com/iamnabink/flutter_esewa/tree/main/example) for more. 
I ran it in IOS simulator and real device and working perfectly fine, let me know if you have any further query. 
Closing this issue for now.

**Closed by iamnabink** 2024-01-23 10:12 UTC
Labels: question
